stages:
- stage: del_rule
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'install'
      inputs:
        terraformVersion: '1.2.0'
      #Azure KEY Vault
    - task: AzureKeyVault@1
      inputs:
        ConnectedServiceName: $(service_name)
        KeyVaultName: $(key_vault_name)
        SecretsFilter: '*'
        RunAsPreJob: false 
    - deployment: del_nsg_rule
      continueOnError: false
      environment: 'spoke14-kv'
      strategy:
        runOnce:
          deploy:
           steps:
             - task: AzureCLI@2
               displayName: 'del nsg'
               inputs:
                  azureSubscription: 'atulavtx-sst2'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az network nsg rule delete --name deploy14 --nsg-name $(controller-nsg)  --resource-group $(controller-rg)'
