stages:
- stage: del_rule
  jobs:
    - deployment: del_nsg_rule
      continueOnError: false
      environment: 'newspoke17'
      strategy:
        runOnce:
          deploy:
           steps:
             - task: AzureCLI@2
               displayName: 'del nsg'
               inputs:
                  azureSubscription: 'atulavtx-sst2'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az network nsg rule delete --name deploy17 --nsg-name $(controller-nsg)  --resource-group $(controller_rg)'
